name: Tests

on:
  push:
    branches: [master, main, compat]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Install Pixi
      uses: prefix-dev/setup-pixi@v0.9.1
      with:
        pixi-version: latest
        manifest-path: pyproject.toml
        cache: true

    - name: Install dependencies
      run: pixi install --manifest-path pyproject.toml

    - name: Run tests
      run: pixi run --manifest-path pyproject.toml pytest tests/ -v
